---
name: Lint Code Base

on:
  pull_request:
    branches: [main]
    paths: ["caddy.dockerfile"]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Lint Dockerfile
        id: hadolint
        uses: hadolint/hadolint-action@3fc49fb50d59c6ab7917a2e4195dba633e515b29 # v3.2.0
        with:
          config: ./.hadolint.yml
          dockerfile: caddy.dockerfile
      - name: Print the linter report
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        if: success() || failure()
        with:
          status: ${{ steps.hadolint.outcome }}
          message: |
            ## Hadolint `${{ steps.hadolint.outcome }}`

            ${{ env.HADOLINT_RESULTS }}
