---
name: Lint Code Base

on:
  pull_request:
    branches: [main]
    paths: ["caddy.dockerfile"]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Lint Dockerfile
        id: hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          config: ./.hadolint.yml
          dockerfile: caddy.dockerfile
      - name: Print the linter report
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        if: success() || failure()
        with:
          status: ${{ steps.hadolint.outcome }}
          message: |
            ## Hadolint `${{ steps.hadolint.outcome }}`

            ${{ env.HADOLINT_RESULTS }}
